### PR TITLE
Add FD.o runtime 19.08 support for beta branch

### PR DESCRIPTION
**Pull request by gasinvein**
19.08 Beta is available, build for it.

### CODE REVIEW

**Comment by refi64** [comment]
Question, how does this work for building? I'm guessing I'd manually create a 19.08beta branch with this commit?

Also as-is install.sh copies Node *and* Python 2, I guess there should now be two install scripts, and only install-sdk.sh would copy everything...though I can make some tweaks and such after this is merged.

**Comment by gasinvein** [comment]
>Question, how does this work for building? I'm guessing I'd manually create a 19.08beta branch with this commit?

I'm not sure if Flathub CI would build `19.08beta` branch. It does build, however, `beta` branch.

>Also as-is install.sh copies Node and Python 2

Python 2 would be needed to build at least nodejs native extensions, so I guess node usage is limited without Python 2.

**Comment by gasinvein** [comment]
Some other SDK extensions use branches like `branch/18.08`. Maybe we should do the same instead of `beta`.

@nedrichards What is the correct way to build this extension for different runtime version (namely 19.08beta)?

**Comment by Erick555** [comment]
Freedesktop Sdk 19.08 is in stable now.

**Comment by gasinvein** [comment]
I guess this is obsolete now.

**Comment by refi64** [comment]
Right, sorry, I basically did it a bit differently with modifying the install scripts that way Python 2 isn't copied into every application.

**Pull request closed without merging**
